on:
  push:

jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      release-branches: '^(master)$'
  
  build:
    name: Spring build
    runs-on: ubuntu-latest
    # si get-version voit un commit qui permet une release (montée de version), il fait le build, sinon fait pas le build
    if: ${{ needs.get-version.outputs.will-release == 'true' }}
    needs:
      - get-version
    steps:
      - name: Print version
        run: echo "${{ needs.get-version.outputs.version }}"
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Gradle
        # variable d'environnement pour que gradle en ait connaissance
        env: 
          VERSION: "${{ needs.get-version.outputs.version }}"
        run: chmod +x gradlew && ./gradlew bootjar
      - run: ls -lia build/libs
      - uses: actions/upload-artifact@v4
        with:
          path: build/libs/
